site_name: Sci-Base
site_url: https://the-documentation-workspace.org
theme:
  name: material
  logo: "Astro Logo Orange.png"
  font:
    code: Roboto Mono
  palette:
    - scheme: default
      primary: black
      accent: black
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - scheme: slate
      primary: black
      accent: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
nav:
  - Home: index.md
  - About: about.md
  - Topics:
      - Overview: topics.md
      - General Relativity: topics/general-relativity.md
      - Vacuum Energy: topics/vacuum-energy.md
      - Gauge Fields: topics/gauge-fields.md
      - Knot Theory: topics/knot-theory.md
      - Quantum Gravity: topics/quantum-gravity.md